import { FacilityCategory, SupportLevel } from './types';

export interface FacilityTemplate {
  type: string;
  name: string;
  defaultWidth: number;
  defaultHeight: number;
  zone: FacilityCategory;
  color: string;
  capacity: number;
  supportLevel: SupportLevel;
  description: string;
  accessibilityNotes: string[];
  careTags: string[];
  styleTags: string[];
  emoji: string;
}

export const FACILITY_TEMPLATES: FacilityTemplate[] = [
  {
    type: 'supported_cottage',
    name: 'Supported Cottage',
    defaultWidth: 60,
    defaultHeight: 50,
    zone: 'residential',
    color: '#D4956A',
    capacity: 2,
    supportLevel: 'medium',
    description: 'Small supported residential cottage for 1-2 residents with on-call support',
    accessibilityNotes: ['step-free access', 'wide doorways', 'accessible bathroom'],
    careTags: ['residential', 'supported-living', 'independence'],
    styleTags: ['timber-clad', 'pitched-roof', 'garden'],
    emoji: '🏡',
  },
  {
    type: 'shared_home',
    name: 'Shared Home',
    defaultWidth: 80,
    defaultHeight: 60,
    zone: 'residential',
    color: '#C8A47A',
    capacity: 4,
    supportLevel: 'medium',
    description: 'Shared residential home for 3-5 residents with shared support',
    accessibilityNotes: ['step-free access', 'assisted bathing', 'hoist-ready rooms'],
    careTags: ['residential', 'shared-living', 'peer-support'],
    styleTags: ['brick', 'pitched-roof', 'shared-garden'],
    emoji: '🏘️',
  },
  {
    type: 'assisted_villa',
    name: 'Assisted Villa',
    defaultWidth: 90,
    defaultHeight: 70,
    zone: 'residential',
    color: '#B89060',
    capacity: 6,
    supportLevel: 'high',
    description: 'Larger assisted living villa with integrated support facilities',
    accessibilityNotes: ['full accessibility', 'hoisting equipment', 'sensory rooms'],
    careTags: ['residential', 'assisted-living', 'clinical-support'],
    styleTags: ['contemporary', 'accessible-design', 'courtyard'],
    emoji: '🏛️',
  },
  {
    type: 'respite_lodge',
    name: 'Respite Lodge',
    defaultWidth: 70,
    defaultHeight: 55,
    zone: 'family_respite',
    color: '#9B7DB8',
    capacity: 3,
    supportLevel: 'high',
    description: 'Short-stay respite accommodation for residents and visiting families',
    accessibilityNotes: ['fully accessible', 'family accommodation', 'en-suite facilities'],
    careTags: ['respite', 'family-support', 'short-stay'],
    styleTags: ['lodge-style', 'natural-materials', 'quiet-setting'],
    emoji: '🛖',
  },
  {
    type: 'adult_care_home',
    name: 'Adult Care Home',
    defaultWidth: 120,
    defaultHeight: 90,
    zone: 'adult_care',
    color: '#E87070',
    capacity: 20,
    supportLevel: 'specialist',
    description: '24/7 higher-support residential and nursing-led care building',
    accessibilityNotes: ['step-free access', 'assisted bathing', 'hoist-ready rooms'],
    careTags: ['clinical', 'residential', 'seizure-support', 'personal-care'],
    styleTags: ['timber-clad', 'pitched-roof', 'courtyard-garden'],
    emoji: '🏥',
  },
  {
    type: 'everyday_centre',
    name: 'Everyday Centre',
    defaultWidth: 110,
    defaultHeight: 80,
    zone: 'community',
    color: '#5BA3D9',
    capacity: 50,
    supportLevel: 'low',
    description: 'Central hub for daily activities, skills building, and social engagement',
    accessibilityNotes: ['full accessibility', 'sensory-calm zones', 'quiet spaces'],
    careTags: ['day-activities', 'skills', 'social', 'community'],
    styleTags: ['open-plan', 'flexible-spaces', 'natural-light'],
    emoji: '🏫',
  },
  {
    type: 'health_hub',
    name: 'Health Hub',
    defaultWidth: 100,
    defaultHeight: 75,
    zone: 'therapy_health',
    color: '#E8A85A',
    capacity: 30,
    supportLevel: 'specialist',
    description: 'Integrated health and therapy centre with clinical consultation rooms',
    accessibilityNotes: ['clinical accessibility', 'sensory-calm design', 'quiet consultation'],
    careTags: ['clinical', 'therapy', 'health', 'consultation'],
    styleTags: ['professional', 'calm-palette', 'flexible'],
    emoji: '⚕️',
  },
  {
    type: 'therapy_suite',
    name: 'Therapy Suite',
    defaultWidth: 85,
    defaultHeight: 65,
    zone: 'therapy_health',
    color: '#F0B870',
    capacity: 15,
    supportLevel: 'specialist',
    description: 'Specialist therapy rooms including OT, physio, hydrotherapy, and sensory integration',
    accessibilityNotes: ['hydrotherapy access', 'sensory equipment', 'quiet environment'],
    careTags: ['therapy', 'clinical', 'sensory-integration', 'physio'],
    styleTags: ['therapeutic-design', 'natural-materials', 'calm'],
    emoji: '🧘',
  },
  {
    type: 'sensory_garden',
    name: 'Sensory Garden',
    defaultWidth: 90,
    defaultHeight: 70,
    zone: 'landscape_sensory',
    color: '#7BC8A4',
    capacity: 20,
    supportLevel: 'low',
    description:
      'Carefully designed garden space with sensory planting, water features, and therapeutic pathways',
    accessibilityNotes: ['fully accessible paths', 'sensory planting', 'safe boundaries'],
    careTags: ['sensory', 'therapeutic', 'outdoor', 'wellbeing'],
    styleTags: ['lush-planting', 'water-feature', 'sensory-zones'],
    emoji: '🌿',
  },
  {
    type: 'community_garden',
    name: 'Community Garden',
    defaultWidth: 100,
    defaultHeight: 80,
    zone: 'landscape_sensory',
    color: '#5CB85C',
    capacity: 30,
    supportLevel: 'low',
    description: 'Productive community growing space with raised beds and accessible growing areas',
    accessibilityNotes: ['raised beds', 'accessible paths', 'adaptive tools available'],
    careTags: ['horticulture', 'community', 'outdoor', 'skills'],
    styleTags: ['productive-landscape', 'raised-beds', 'orchard'],
    emoji: '🌱',
  },
  {
    type: 'greenhouse',
    name: 'Greenhouse',
    defaultWidth: 70,
    defaultHeight: 40,
    zone: 'landscape_sensory',
    color: '#B8D96A',
    capacity: 15,
    supportLevel: 'low',
    description: 'Year-round growing facility for therapeutic horticulture and food production',
    accessibilityNotes: ['wheelchair accessible', 'adapted tools', 'wide aisles'],
    careTags: ['horticulture', 'skills', 'food-production', 'therapeutic'],
    styleTags: ['glass-structure', 'productive', 'sustainable'],
    emoji: '🌾',
  },
  {
    type: 'community_centre',
    name: 'Community Centre',
    defaultWidth: 100,
    defaultHeight: 75,
    zone: 'community',
    color: '#4A90D9',
    capacity: 80,
    supportLevel: 'low',
    description:
      'Multi-purpose community building for village events, family meetings, and shared activities',
    accessibilityNotes: ['full accessibility', 'hearing loops', 'quiet spaces'],
    careTags: ['community', 'events', 'social', 'family'],
    styleTags: ['community-hall', 'flexible-layout', 'welcoming'],
    emoji: '🏪',
  },
  {
    type: 'accessible_cafe',
    name: 'Accessible Café',
    defaultWidth: 80,
    defaultHeight: 55,
    zone: 'community',
    color: '#D4956A',
    capacity: 40,
    supportLevel: 'low',
    description:
      'Community café providing accessible dining, social space, and employment opportunities',
    accessibilityNotes: ['wheelchair accessible', 'sensory-calm design', 'inclusive menu'],
    careTags: ['community', 'social', 'employment', 'food'],
    styleTags: ['café-style', 'warm-interior', 'outdoor-seating'],
    emoji: '☕',
  },
  {
    type: 'family_hub',
    name: 'Family Hub',
    defaultWidth: 85,
    defaultHeight: 65,
    zone: 'family_respite',
    color: '#C494D4',
    capacity: 25,
    supportLevel: 'low',
    description:
      'Dedicated family support centre with counselling, family rooms, and overnight accommodation',
    accessibilityNotes: ['family-friendly layout', 'accessible throughout', 'quiet spaces'],
    careTags: ['family-support', 'counselling', 'community', 'respite'],
    styleTags: ['homely', 'welcoming', 'flexible-spaces'],
    emoji: '👨‍👩‍👧',
  },
  {
    type: 'inclusive_play',
    name: 'Inclusive Play Area',
    defaultWidth: 80,
    defaultHeight: 70,
    zone: 'recreational',
    color: '#F0C060',
    capacity: 25,
    supportLevel: 'low',
    description: 'Fully inclusive play area with accessible play equipment for all abilities',
    accessibilityNotes: ['wheelchair-accessible equipment', 'safe surfacing', 'sensory play'],
    careTags: ['play', 'inclusive', 'recreational', 'sensory'],
    styleTags: ['colourful', 'natural-play', 'accessible-equipment'],
    emoji: '🛝',
  },
  {
    type: 'adaptive_sports',
    name: 'Adaptive Sports Area',
    defaultWidth: 120,
    defaultHeight: 90,
    zone: 'recreational',
    color: '#E8D050',
    capacity: 30,
    supportLevel: 'low',
    description:
      'Multi-use sports and recreation area with adaptive equipment and accessible surfaces',
    accessibilityNotes: ['accessible surfaces', 'adaptive equipment', 'clear wayfinding'],
    careTags: ['sports', 'recreation', 'physical-activity', 'adaptive'],
    styleTags: ['open-air', 'multi-use', 'inclusive-design'],
    emoji: '🏃',
  },
  {
    type: 'transport_hub',
    name: 'Transport Hub',
    defaultWidth: 90,
    defaultHeight: 50,
    zone: 'operations_services',
    color: '#90A0B4',
    capacity: 0,
    supportLevel: 'low',
    description:
      'Accessible transport node with accessible vehicles, drop-off areas, and wayfinding',
    accessibilityNotes: ['accessible vehicles', 'level boarding', 'clear signage'],
    careTags: ['transport', 'operations', 'accessibility'],
    styleTags: ['functional', 'covered', 'wayfinding'],
    emoji: '🚌',
  },
  {
    type: 'parking',
    name: 'Parking',
    defaultWidth: 110,
    defaultHeight: 60,
    zone: 'operations_services',
    color: '#A0A8B8',
    capacity: 0,
    supportLevel: 'low',
    description:
      'Accessible parking area including disabled bays, visitor parking, and staff parking',
    accessibilityNotes: ['disabled bays', 'level surfaces', 'close to entrance'],
    careTags: ['parking', 'operations', 'accessibility'],
    styleTags: ['paved', 'marked-bays', 'landscaped-edges'],
    emoji: '🅿️',
  },
  {
    type: 'rental_training',
    name: 'Rental / Training Unit',
    defaultWidth: 90,
    defaultHeight: 55,
    zone: 'commercial_training',
    color: '#D4A060',
    capacity: 20,
    supportLevel: 'low',
    description:
      'Flexible commercial and training units generating income while providing training opportunities',
    accessibilityNotes: ['accessible throughout', 'flexible layout', 'community access'],
    careTags: ['training', 'employment', 'commercial', 'skills'],
    styleTags: ['flexible-units', 'commercial-frontage', 'community-facing'],
    emoji: '🏢',
  },
  {
    type: 'utility_plant',
    name: 'Utility Plant',
    defaultWidth: 80,
    defaultHeight: 60,
    zone: 'operations_services',
    color: '#808898',
    capacity: 0,
    supportLevel: 'low',
    description:
      'Central utilities building housing energy systems, water plant, and infrastructure',
    accessibilityNotes: ['staff access only', 'secure perimeter'],
    careTags: ['utilities', 'operations', 'infrastructure', 'sustainability'],
    styleTags: ['functional', 'screened', 'low-impact'],
    emoji: '⚙️',
  },
  {
    type: 'workshop_maintenance',
    name: 'Workshop / Maintenance',
    defaultWidth: 75,
    defaultHeight: 55,
    zone: 'operations_services',
    color: '#889098',
    capacity: 10,
    supportLevel: 'low',
    description: 'Maintenance workshop and craft spaces for repair, making, and skilled activities',
    accessibilityNotes: ['accessible workshop', 'adapted tools', 'ventilation'],
    careTags: ['maintenance', 'skills', 'craft', 'operations'],
    styleTags: ['industrial-light', 'practical', 'craft-focused'],
    emoji: '🔧',
  },
  {
    type: 'staff_base',
    name: 'Staff Base',
    defaultWidth: 70,
    defaultHeight: 50,
    zone: 'operations_services',
    color: '#9898A8',
    capacity: 20,
    supportLevel: 'low',
    description:
      'Staff facilities including offices, break rooms, training, and welfare facilities',
    accessibilityNotes: ['accessible staff facilities', 'welfare rooms', 'training space'],
    careTags: ['staff', 'operations', 'training', 'welfare'],
    styleTags: ['professional', 'efficient', 'well-equipped'],
    emoji: '👥',
  },
  {
    type: 'custom_facility',
    name: 'Custom Facility',
    defaultWidth: 80,
    defaultHeight: 60,
    zone: 'community',
    color: '#B8A890',
    capacity: 10,
    supportLevel: 'low',
    description: 'Custom facility - edit name and details in the inspector',
    accessibilityNotes: [],
    careTags: [],
    styleTags: [],
    emoji: '📦',
  },
];

export const ZONE_COLORS: Record<string, string> = {
  residential: '#D4956A',
  adult_care: '#E87070',
  therapy_health: '#E8A85A',
  community: '#5BA3D9',
  family_respite: '#9B7DB8',
  recreational: '#F0C060',
  operations_services: '#90A0B4',
  commercial_training: '#D4A060',
  landscape_sensory: '#7BC8A4',
};

export const ZONE_LABELS: Record<string, string> = {
  residential: 'Residential',
  adult_care: 'Adult Care',
  therapy_health: 'Therapy & Health',
  community: 'Community',
  family_respite: 'Family & Respite',
  recreational: 'Recreational',
  operations_services: 'Operations & Services',
  commercial_training: 'Commercial & Training',
  landscape_sensory: 'Landscape & Sensory',
};
